apiVersion: v1
kind: Service
metadata:
  name: capi-kubeadm-control-plane-webhook-service
  namespace: capi-webhook-system
  labels:
    cluster.x-k8s.io/provider: control-plane-kubeadm
    clusterctl.cluster.x-k8s.io: ""
    clusterctl.cluster.x-k8s.io/lifecycle: shared
spec:
  selector:
    cluster.x-k8s.io/provider: control-plane-kubeadm
  ports:
    - protocol: TCP
      port: 443
      targetPort: webhook-server
