apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: caps-serving-cert
  namespace: capi-webhook-system
  labels:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
spec:
  dnsNames:
    - caps-webhook-service.capi-webhook-system.svc
    - caps-webhook-service.capi-webhook-system.svc.cluster.local
  issuerRef:
    name: caps-selfsigned-issuer
    kind: Issuer
  secretName: caps-webhook-service-cert
