apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: caps-selfsigned-issuer
  namespace: capi-webhook-system
  labels:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    clusterctl.cluster.x-k8s.io: ""
    clusterctl.cluster.x-k8s.io/lifecycle: shared
spec:
  selfSigned: {}
