apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager:leaderelection
  namespace: kube-system
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
roleRef:
  name: cert-manager:leaderelection
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: cert-manager
    namespace: cert-manager
    kind: ServiceAccount
    apiGroup: ""
