apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-cainjector:leaderelection
  namespace: kube-system
  labels:
    app: cainjector
    app.kubernetes.io/component: cainjector
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cainjector
roleRef:
  name: cert-manager-cainjector:leaderelection
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: cert-manager-cainjector
    namespace: cert-manager
    kind: ServiceAccount
