apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: capd-selfsigned-issuer
  namespace: capd-system
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
spec:
  selfSigned: {}
