apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capd-leader-election-rolebinding
  namespace: capd-system
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
    clusterctl.cluster.x-k8s.io: ""
roleRef:
  name: capd-leader-election-role
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: default
    namespace: capd-system
    kind: ServiceAccount
