apiVersion: v1
kind: Service
metadata:
  name: capd-controller-manager-metrics-service
  namespace: capd-system
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
    control-plane: controller-manager
    clusterctl.cluster.x-k8s.io: ""
  annotations:
    prometheus.io/port: "8443"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
spec:
  selector:
    cluster.x-k8s.io/provider: infrastructure-docker
    control-plane: controller-manager
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: https
