apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cacppt-leader-election-rolebinding
  namespace: cacppt-system
  labels:
    cluster.x-k8s.io/provider: controlplane-talos
    clusterctl.cluster.x-k8s.io: ""
roleRef:
  name: cacppt-leader-election-role
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: default
    namespace: cacppt-system
    kind: ServiceAccount
