apiVersion: apps/v1
kind: Deployment
metadata:
  name: capd-controller-manager
  namespace: capd-system
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
    clusterctl.cluster.x-k8s.io: ""
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: infrastructure-docker
      control-plane: controller-manager
  template:
    metadata:
      labels:
        cluster.x-k8s.io/provider: infrastructure-docker
        control-plane: controller-manager
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: kube-rbac-proxy
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
          args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10
          ports:
            - name: https
              containerPort: 8443
        - name: manager
          image: gcr.io/k8s-staging-cluster-api/capd-manager:v0.3.16
          args:
            - --feature-gates=MachinePool=$(EXP_MACHINE_POOL),ClusterResourceSet=$(EXP_CLUSTER_RESOURCE_SET)
            - --metrics-addr=0
            - -v=4
          ports:
            - name: webhook-server
              protocol: TCP
              containerPort: 9443
            - name: healthz
              protocol: TCP
              containerPort: 9440
          env:
            - name: EXP_MACHINE_POOL
              value: "false" # kpt-set: ${EXP_MACHINE_POOL}
            - name: EXP_CLUSTER_RESOURCE_SET
              value: "false" # kpt-set: ${EXP_CLUSTER_RESOURCE_SET}
          volumeMounts:
            - name: cert
              readOnly: true
              mountPath: /tmp/k8s-webhook-server/serving-certs
            - name: dockersock
              mountPath: /var/run/docker.sock
          livenessProbe:
            httpGet:
              port: healthz
              path: /healthz
          readinessProbe:
            httpGet:
              port: healthz
              path: /readyz
          securityContext:
            privileged: true
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: capd-webhook-service-cert
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
