apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: capd-leader-election-role
  namespace: capd-system
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
    clusterctl.cluster.x-k8s.io: ""
rules:
  - resources:
      - configmaps
    apiGroups:
      - ""
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - resources:
      - configmaps/status
    apiGroups:
      - ""
    verbs:
      - get
      - update
      - patch
  - resources:
      - events
    apiGroups:
      - ""
    verbs:
      - create
