apiVersion: v1
kind: Service
metadata:
  name: capd-webhook-service
  namespace: capd-system
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
    clusterctl.cluster.x-k8s.io: ""
spec:
  selector:
    cluster.x-k8s.io/provider: infrastructure-docker
    control-plane: controller-manager
  ports:
    - port: 443
      targetPort: 9443
