apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cacppt-metrics-reader
  labels:
    cluster.x-k8s.io/provider: controlplane-talos
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
