apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cacppt-proxy-role
  labels:
    cluster.x-k8s.io/provider: controlplane-talos
rules:
  - resources:
      - tokenreviews
    apiGroups:
      - authentication.k8s.io
    verbs:
      - create
  - resources:
      - subjectaccessreviews
    apiGroups:
      - authorization.k8s.io
    verbs:
      - create
