apiVersion: v1
kind: Service
metadata:
  name: capi-kubeadm-control-plane-controller-manager-metrics-service
  namespace: capi-kubeadm-control-plane-system
  labels:
    cluster.x-k8s.io/provider: control-plane-kubeadm
    control-plane: controller-manager
spec:
  selector:
    cluster.x-k8s.io/provider: control-plane-kubeadm
    control-plane: controller-manager
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: https
