apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capi-leader-election-rolebinding
  namespace: capi-system # kpt-set: ${NAMESPACE}
  labels:
    cluster.x-k8s.io/provider: cluster-api
    clusterctl.cluster.x-k8s.io: ""
roleRef:
  name: capi-leader-election-role
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: default
    namespace: capi-system # kpt-set: ${NAMESPACE}
    kind: ServiceAccount
