apiVersion: v1
kind: Service
metadata:
  name: capi-controller-manager-metrics-service
  namespace: capi-system # kpt-set: ${NAMESPACE}
  labels:
    cluster.x-k8s.io/provider: cluster-api
    clusterctl.cluster.x-k8s.io: ""
    control-plane: controller-manager
spec:
  selector:
    cluster.x-k8s.io/provider: cluster-api
    control-plane: controller-manager
  ports:
    - name: https
      port: 8443
      targetPort: https
