apiVersion: apps/v1
kind: Deployment
metadata:
  name: cacppt-controller-manager
  namespace: cacppt-system
  labels:
    cluster.x-k8s.io/provider: controlplane-talos
    control-plane: controller-manager
    clusterctl.cluster.x-k8s.io: ""
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: controlplane-talos
      control-plane: controller-manager
  template:
    metadata:
      labels:
        cluster.x-k8s.io/provider: controlplane-talos
        control-plane: controller-manager
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: manager
          image: ghcr.io/talos-systems/cluster-api-control-plane-talos-controller:v0.1.0-alpha.13
          command:
            - /manager
          args:
            - --enable-leader-election
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 128Mi
          imagePullPolicy: Always
