apiVersion: v1
kind: Service
metadata:
  name: cacppt-controller-manager-metrics-service
  namespace: cacppt-system
  labels:
    cluster.x-k8s.io/provider: controlplane-talos
    control-plane: controller-manager
spec:
  selector:
    cluster.x-k8s.io/provider: controlplane-talos
    control-plane: controller-manager
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: https
