apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capi-kubeadm-control-plane-aggregated-manager-role
  labels:
    cluster.x-k8s.io/provider: control-plane-kubeadm
    clusterctl.cluster.x-k8s.io: ""
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        kubeadm.controlplane.cluster.x-k8s.io/aggregate-to-manager: "true"
rules: []
