apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: capi-kubeadm-control-plane-mutating-webhook-configuration
  labels:
    cluster.x-k8s.io/provider: control-plane-kubeadm
  annotations:
    cert-manager.io/inject-ca-from: capi-webhook-system/capi-kubeadm-control-plane-serving-cert
webhooks:
  - name: default.kubeadmcontrolplane.controlplane.cluster.x-k8s.io
    clientConfig:
      service:
        name: capi-kubeadm-control-plane-webhook-service
        namespace: capi-webhook-system
        path: /mutate-controlplane-cluster-x-k8s-io-v1alpha3-kubeadmcontrolplane
    failurePolicy: Fail
    matchPolicy: Equivalent
    rules:
      - resources:
          - kubeadmcontrolplanes
        apiGroups:
          - controlplane.cluster.x-k8s.io
        apiVersions:
          - v1alpha3
        operations:
          - CREATE
          - UPDATE
    sideEffects: None
