apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sidero-server
  labels:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    clusterctl.cluster.x-k8s.io: ""
roleRef:
  name: sidero-metadata-server-role
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: default
    namespace: sidero-system
    kind: ServiceAccount
