apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sidero-serverclass-editor-role
  labels:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    clusterctl.cluster.x-k8s.io: ""
rules:
  - resources:
      - serverclasses
    apiGroups:
      - metal.sidero.dev
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - resources:
      - serverclasses/status
    apiGroups:
      - metal.sidero.dev
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
