apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capi-kubeadm-control-plane-leader-election-rolebinding
  namespace: capi-kubeadm-control-plane-system
  labels:
    cluster.x-k8s.io/provider: control-plane-kubeadm
    clusterctl.cluster.x-k8s.io: ""
roleRef:
  name: capi-kubeadm-control-plane-leader-election-role
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: default
    namespace: capi-kubeadm-control-plane-system
    kind: ServiceAccount
