apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capi-kubeadm-control-plane-proxy-role
  labels:
    cluster.x-k8s.io/provider: control-plane-kubeadm
    clusterctl.cluster.x-k8s.io: ""
rules:
  - resources:
      - tokenreviews
    apiGroups:
      - authentication.k8s.io
    verbs:
      - create
  - resources:
      - subjectaccessreviews
    apiGroups:
      - authorization.k8s.io
    verbs:
      - create
