apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidero-metadata-server
  namespace: sidero-system
  labels:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidero
      cluster.x-k8s.io/provider: sidero
      cluster.x-k8s.io/v1alpha3: v1alpha3
      control-plane: metal-metadata-server
  template:
    metadata:
      labels:
        app: sidero
        cluster.x-k8s.io/provider: sidero
        cluster.x-k8s.io/v1alpha3: v1alpha3
        control-plane: metal-metadata-server
    spec:
      terminationGracePeriodSeconds: 10
      hostNetwork: ${SIDERO_METADATA_SERVER_HOST_NETWORK:=false}
      containers:
        - name: server
          image: ghcr.io/talos-systems/metal-metadata-server:v0.3.0-alpha.0
          args:
            - --port=${SIDERO_METADATA_SERVER_PORT:=8080}
          ports:
            - name: http
              protocol: TCP
              containerPort: ${SIDERO_METADATA_SERVER_PORT:=8080}
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          imagePullPolicy: Always
