apiVersion: apps/v1
kind: Deployment
metadata:
  name: caps-controller-manager
  namespace: sidero-system
  labels:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    control-plane: caps-controller-manager
    clusterctl.cluster.x-k8s.io: ""
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidero
      cluster.x-k8s.io/provider: sidero
      cluster.x-k8s.io/v1alpha3: v1alpha3
      control-plane: caps-controller-manager
  template:
    metadata:
      labels:
        app: sidero
        cluster.x-k8s.io/provider: sidero
        cluster.x-k8s.io/v1alpha3: v1alpha3
        control-plane: caps-controller-manager
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: manager
          image: ghcr.io/talos-systems/cluster-api-provider-sidero:v0.3.0-alpha.0
          command:
            - /manager
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          imagePullPolicy: Always
