apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: caps-leader-election-rolebinding
  namespace: sidero-system
  labels:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    clusterctl.cluster.x-k8s.io: ""
roleRef:
  name: caps-leader-election-role
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: default
    namespace: sidero-system
    kind: ServiceAccount
