apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: caps-leader-election-role
  namespace: sidero-system
  labels:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    clusterctl.cluster.x-k8s.io: ""
rules:
  - resources:
      - configmaps
    apiGroups:
      - ""
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - resources:
      - configmaps/status
    apiGroups:
      - ""
    verbs:
      - get
      - update
      - patch
  - resources:
      - events
    apiGroups:
      - ""
    verbs:
      - create
