apiVersion: v1
kind: Service
metadata:
  name: sidero-ipxe
  namespace: sidero-system
  labels:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    clusterctl.cluster.x-k8s.io: ""
spec:
  selector:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    control-plane: metal-controller-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
