apiVersion: v1
kind: Service
metadata:
  name: sidero-tftp
  namespace: sidero-system
  labels:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
spec:
  selector:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    control-plane: metal-controller-manager
  ports:
    - protocol: UDP
      port: 69
      targetPort: tftp
