apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capi-system-capi-manager-role
  labels:
    cluster.x-k8s.io/aggregate-to-manager: "true"
    cluster.x-k8s.io/provider: cluster-api
    clusterctl.cluster.x-k8s.io: ""
rules:
  - resources:
      - '*'
    apiGroups:
      - addons.cluster.x-k8s.io
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - resources:
      - clusterresourcesets/status
    apiGroups:
      - addons.cluster.x-k8s.io
    verbs:
      - get
      - patch
      - update
  - resources:
      - customresourcedefinitions
    apiGroups:
      - apiextensions.k8s.io
    verbs:
      - get
      - list
      - watch
  - resources:
      - '*'
    apiGroups:
      - bootstrap.cluster.x-k8s.io
      - controlplane.cluster.x-k8s.io
      - infrastructure.cluster.x-k8s.io
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - resources:
      - '*'
    apiGroups:
      - bootstrap.cluster.x-k8s.io
      - exp.infrastructure.cluster.x-k8s.io
      - infrastructure.cluster.x-k8s.io
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - resources:
      - '*'
    apiGroups:
      - bootstrap.cluster.x-k8s.io
      - infrastructure.cluster.x-k8s.io
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - resources:
      - clusters
      - clusters/status
    apiGroups:
      - cluster.x-k8s.io
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - resources:
      - machinedeployments
      - machinedeployments/status
    apiGroups:
      - cluster.x-k8s.io
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - resources:
      - machinehealthchecks
      - machinehealthchecks/status
    apiGroups:
      - cluster.x-k8s.io
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - resources:
      - machines
      - machines/status
    apiGroups:
      - cluster.x-k8s.io
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - resources:
      - machinesets
      - machinesets/status
    apiGroups:
      - cluster.x-k8s.io
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - resources:
      - configmaps
    apiGroups:
      - ""
    verbs:
      - get
      - list
      - patch
      - watch
  - resources:
      - events
    apiGroups:
      - ""
    verbs:
      - create
      - get
      - list
      - patch
      - watch
  - resources:
      - nodes
    apiGroups:
      - ""
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - resources:
      - secrets
    apiGroups:
      - ""
    verbs:
      - create
      - get
      - list
      - patch
      - watch
  - resources:
      - '*'
    apiGroups:
      - exp.cluster.x-k8s.io
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - resources:
      - machinepools
      - machinepools/status
    apiGroups:
      - exp.cluster.x-k8s.io
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
