apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: caps-metalcluster-editor-role-rolebinding
  labels:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
roleRef:
  name: caps-manager-role
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: default
    namespace: sidero-system
    kind: ServiceAccount
