apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: capi-serving-cert
  namespace: capi-webhook-system
  labels:
    cluster.x-k8s.io/provider: cluster-api
spec:
  dnsNames:
    - capi-webhook-service.capi-webhook-system.svc
    - capi-webhook-service.capi-webhook-system.svc.cluster.local
  issuerRef:
    name: capi-selfsigned-issuer
    kind: Issuer
  secretName: capi-webhook-service-cert
