apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: capi-selfsigned-issuer
  namespace: capi-webhook-system
  labels:
    cluster.x-k8s.io/provider: cluster-api
spec:
  selfSigned: {}
