apiVersion: v1
kind: Service
metadata:
  name: capi-webhook-service
  namespace: capi-webhook-system
  labels:
    cluster.x-k8s.io/provider: cluster-api
spec:
  selector:
    cluster.x-k8s.io/provider: cluster-api
  ports:
    - protocol: TCP
      port: 443
      targetPort: webhook-server
