apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capi-system-manager-rolebinding # kpt-set: ${NAMESPACE}-manager-rolebinding
  labels:
    cluster.x-k8s.io/provider: cluster-api
    clusterctl.cluster.x-k8s.io: ""
roleRef:
  name: capi-system-aggregated-manager-role # kpt-set: ${NAMESPACE}-aggregated-manager-role
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: default
    namespace: capi-system # kpt-set: ${NAMESPACE}
    kind: ServiceAccount
