apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capi-system-proxy-role # kpt-set: ${NAMESPACE}-proxy-role
  labels:
    cluster.x-k8s.io/provider: cluster-api
    clusterctl.cluster.x-k8s.io: ""
rules:
  - resources:
      - tokenreviews
    apiGroups:
      - authentication.k8s.io
    verbs:
      - create
  - resources:
      - subjectaccessreviews
    apiGroups:
      - authorization.k8s.io
    verbs:
      - create
