apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capd-proxy-rolebinding
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
roleRef:
  name: capd-proxy-role
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: default
    namespace: capd-system
    kind: ServiceAccount
