apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: capd-validating-webhook-configuration
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
  annotations:
    cert-manager.io/inject-ca-from: capd-system/capd-serving-cert
  creationTimestamp: "null"
webhooks:
  - name: validation.dockermachinetemplate.infrastructure.cluster.x-k8s.io
    clientConfig:
      service:
        name: capd-webhook-service
        namespace: capd-system
        path: /validate-infrastructure-cluster-x-k8s-io-v1alpha3-dockermachinetemplate
      caBundle: Cg==
    failurePolicy: Fail
    matchPolicy: Equivalent
    rules:
      - resources:
          - dockermachinetemplates
        apiGroups:
          - infrastructure.cluster.x-k8s.io
        apiVersions:
          - v1alpha3
        operations:
          - CREATE
          - UPDATE
    sideEffects: None
