apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-controller-challenges
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
rules:
  - resources:
      - challenges
      - challenges/status
    apiGroups:
      - acme.cert-manager.io
    verbs:
      - update
  - resources:
      - challenges
    apiGroups:
      - acme.cert-manager.io
    verbs:
      - get
      - list
      - watch
  - resources:
      - issuers
      - clusterissuers
    apiGroups:
      - cert-manager.io
    verbs:
      - get
      - list
      - watch
  - resources:
      - secrets
    apiGroups:
      - ""
    verbs:
      - get
      - list
      - watch
  - resources:
      - events
    apiGroups:
      - ""
    verbs:
      - create
      - patch
  - resources:
      - pods
      - services
    apiGroups:
      - ""
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - resources:
      - ingresses
    apiGroups:
      - networking.k8s.io
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
  - resources:
      - routes/custom-host
    apiGroups:
      - route.openshift.io
    verbs:
      - create
  - resources:
      - challenges/finalizers
    apiGroups:
      - acme.cert-manager.io
    verbs:
      - update
  - resources:
      - secrets
    apiGroups:
      - ""
    verbs:
      - get
      - list
      - watch
