apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-view
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - resources:
      - certificates
      - certificaterequests
      - issuers
    apiGroups:
      - cert-manager.io
    verbs:
      - get
      - list
      - watch
  - resources:
      - challenges
      - orders
    apiGroups:
      - acme.cert-manager.io
    verbs:
      - get
      - list
      - watch
