apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-controller-ingress-shim
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
rules:
  - resources:
      - certificates
      - certificaterequests
    apiGroups:
      - cert-manager.io
    verbs:
      - create
      - update
      - delete
  - resources:
      - certificates
      - certificaterequests
      - issuers
      - clusterissuers
    apiGroups:
      - cert-manager.io
    verbs:
      - get
      - list
      - watch
  - resources:
      - ingresses
    apiGroups:
      - networking.k8s.io
    verbs:
      - get
      - list
      - watch
  - resources:
      - ingresses/finalizers
    apiGroups:
      - networking.k8s.io
    verbs:
      - update
  - resources:
      - events
    apiGroups:
      - ""
    verbs:
      - create
      - patch
