apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-clusterissuers
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
roleRef:
  name: cert-manager-controller-clusterissuers
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: cert-manager
    namespace: cert-manager
    kind: ServiceAccount
