apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.3.16/core-components.yaml

components:
  - ../common/cluster-api

images:
  - name: gcr.io/k8s-staging-cluster-api/cluster-api-controller
    newName: us.gcr.io/k8s-artifacts-prod/cluster-api/cluster-api-controller
    newTag: v0.3.16

patches:
  - target:
      kind: ClusterRole
      name: capi-aggregated-manager-role
    patch: |-
      - op: replace
        path: /metadata/name
        value: capi-system-capi-aggregated-manager-role
      - op: remove
        path: /rules

  - target:
      kind: ClusterRole
      name: capi-manager-role
    patch: |-
      - op: replace
        path: /metadata/name
        value: capi-system-capi-manager-role

  - target:
      kind: ClusterRole
      name: capi-proxy-role
    patch: |-
      - op: replace
        path: /metadata/name
        value: capi-system-capi-proxy-role

  - target:
      kind: ClusterRoleBinding
      name: capi-manager-rolebinding
    patch: |-
      - op: replace
        path: /metadata/name
        value: capi-system-capi-manager-rolebinding

  - target:
      kind: ClusterRoleBinding
      name: capi-proxy-rolebinding
    patch: |-
      - op: replace
        path: /metadata/name
        value: capi-system-capi-proxy-rolebinding
